# -*- coding: utf-8 -*-
"""f2387-ch01-decision-tree-classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aJ5UzVLmG5-_R8PVUm4N3n9CGddh7woI
"""

# ---第 1 部分---
# 載入函式庫與資料
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_breast_cancer
from sklearn import metrics
bc = load_breast_cancer()

# ---第 2 部分---
# 把資料分為訓練資料集與驗證資料集
train_x, train_y = bc.data[:400], bc.target[:400]
test_x, test_y = bc.data[400:], bc.target[400:]

# ---第3 部分---
# 初始化、訓練並評估模型
tree = DecisionTreeClassifier(random_state = 0, max_depth = 2)
tree.fit(train_x, train_y)
acc = metrics.accuracy_score(test_y, tree.predict(test_x))

# ---第 4部分---
# 顯示模型訓練結果
print('---Decision Tree on breast cancer dataset---')
print('Accuracy: %.2f \n'%acc)
print(metrics.confusion_matrix(test_y, tree.predict(test_x)))

from sklearn.tree import export_graphviz
import graphviz
dot = export_graphviz(tree, 
                      feature_names = bc.feature_names, 
                      class_names = bc.target_names, 
                      impurity = False)
graphviz.Source(dot)